INSERT IGNORE INTO coins (
  id, name, symbol, symbol2, algo, block_explorer, index_avg, txfee, payout_min, payout_max,
  block_time, difficulty, block_height, reward, reward_mul, mature_blocks, enable, auto_ready,
  visible, no_explorer, created, conf_folder, program, rpcuser, rpcpasswd, rpchost, rpcport,
  rpcencoding, account, hasgetinfo, hassubmitblock, hasmasternodes, usememorypool, usesegwit,
  txmessage, auxpow, multialgos, installed, watch, link_site, link_github, link_explorer
) VALUES
  (61,  'Flopcoin', 'FLOP',  '', 'scrypt', '',                                        9, 0.001, 0.001, NULL,  60, 1, 0, 0,     1, 240, 1, 1, 1, 1, UNIX_TIMESTAMP(), '.flopcoin',  'flopcoind',  'umbrel', 'umbrel', 'daemons', 32551,  'POW', '', 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 'https://flopcoin.lovable.app', 'https://github.com/Flopcoin/Flopcoin', 'https://explorer.flopcoin.net'),
  (334, 'CraftCoin', 'CRC',   '', 'scrypt', '',                                       10, 0.001, 0.001, NULL,  60, 1, 0, 0,     1, 240, 1, 1, 1, 1, UNIX_TIMESTAMP(), '.craftcoin', 'craftcoind', 'umbrel', 'umbrel', 'daemons', 12124,  'POW', '', 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 'https://craftcoin.info', 'https://github.com/craftcoin2013/craftcoinV3', '')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  symbol = VALUES(symbol),
  algo = VALUES(algo),
  block_explorer = VALUES(block_explorer),
  index_avg = VALUES(index_avg),
  txfee = VALUES(txfee),
  payout_min = VALUES(payout_min),
  payout_max = VALUES(payout_max),
  block_time = VALUES(block_time),
  difficulty = VALUES(difficulty),
  block_height = VALUES(block_height),
  reward = VALUES(reward),
  reward_mul = VALUES(reward_mul),
  mature_blocks = VALUES(mature_blocks),
  enable = VALUES(enable),
  auto_ready = VALUES(auto_ready),
  visible = VALUES(visible),
  no_explorer = VALUES(no_explorer),
  conf_folder = VALUES(conf_folder),
  program = VALUES(program),
  rpcuser = VALUES(rpcuser),
  rpcpasswd = VALUES(rpcpasswd),
  rpchost = VALUES(rpchost),
  rpcport = VALUES(rpcport),
  rpcencoding = VALUES(rpcencoding),
  hasgetinfo = VALUES(hasgetinfo),
  hassubmitblock = VALUES(hassubmitblock),
  hasmasternodes = VALUES(hasmasternodes),
  usememorypool = VALUES(usememorypool),
  usesegwit = VALUES(usesegwit),
  txmessage = VALUES(txmessage),
  auxpow = VALUES(auxpow),
  multialgos = VALUES(multialgos),
  installed = VALUES(installed),
  watch = VALUES(watch),
  link_site = VALUES(link_site),
  link_github = VALUES(link_github),
  link_explorer = VALUES(link_explorer);
