#!/bin/bash

export APP_PEERCOIN_POOL_STRATUM_PORT="2028"
export APP_PEERCOIN_POOL_RPC_PORT="9902"
export APP_PEERCOIN_POOL_RPC_USER="peercoin"
export APP_PEERCOIN_POOL_RPC_PASSWORD="peercoinrpc"
export APP_PEERCOIN_POOL_IDENTIFIER="HappyChina PPC"
